from django.contrib import admin
from . models import *

# Register your models here.

admin.site.register(Pathologist)
admin.site.register(Medtech)
admin.site.register(Transaction)
admin.site.register(Specimen)
admin.site.register(Patient)
admin.site.register(Complete_Blood_Count)
admin.site.register(BloodTyping)
admin.site.register(ESR)
admin.site.register(FBS)
admin.site.register(Cholesterol)
admin.site.register(Triglyceride)
admin.site.register(HDL)
admin.site.register(LDL)
admin.site.register(BUN)
admin.site.register(Creatine)
admin.site.register(BUA)
admin.site.register(AST)
admin.site.register(ALT)
admin.site.register(Sodium)
admin.site.register(Potassium)
admin.site.register(Calcium)
admin.site.register(Urinalysis)
admin.site.register(Pregnancy_Test)
admin.site.register(FOBT)
admin.site.register(ASO)
admin.site.register(Dengue_Antibody)
admin.site.register(Dengue_Antigen)