# Generated by Django 5.0 on 2023-12-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medtech',
            fields=[
                ('medtechid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('medtechname', models.CharField(default='Medtech Name', max_length=100)),
                ('prcid', models.CharField(default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('pathoid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('pathoname', models.CharField(default='Patho Name', max_length=100)),
                ('prcid', models.CharField(default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('patientlastname', models.CharField(max_length=100, null=True)),
                ('patientfirstname', models.CharField(max_length=100, null=True)),
                ('patientmiddlename', models.CharField(blank=True, max_length=100, null=True)),
                ('dateofbirth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8)),
                ('patient_age_new', models.IntegerField()),
                ('requesting_physician', models.CharField(default='DefaultPhysicianName', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Clinic',
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('specimenid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('medtechid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medtech')),
                ('patientid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testid', models.CharField(default=1, max_length=20)),
                ('testcode', models.CharField(default=1, max_length=3)),
                ('datetime', models.CharField(default=1, max_length=20)),
                ('pathoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pathologist')),
                ('patientid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specimen')),
            ],
        ),
        migrations.CreateModel(
            name='Sodium',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=16, max_length=3)),
                ('sodium', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy_Test',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=20, max_length=3)),
                ('pregnancy_result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Potassium',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=17, max_length=3)),
                ('potassium', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='LDL',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=8, max_length=3)),
                ('ldl', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HDL',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=7, max_length=3)),
                ('hdl', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FOBT',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=22, max_length=3)),
                ('fobt', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Fecalysis',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=21, max_length=3)),
                ('color_appearance', models.CharField(choices=[('yellow', 'yellow'), ('brown', 'brown'), ('black', 'black')], max_length=6)),
                ('consistency', models.CharField(choices=[('formed', 'formed'), ('semi-formed', 'semi-formed'), ('watery', 'watery')], max_length=11)),
                ('mucus', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('blood', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('pus_cells', models.FloatField(default=0.0)),
                ('rbc', models.FloatField(default=0.0)),
                ('ova', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('cyst', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('bacteria', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('other', models.CharField(max_length=50, null=True)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FBS',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=4, max_length=3)),
                ('fbs', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ESR',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=3, max_length=3)),
                ('esr', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Dengue_Antigen',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=25, max_length=3)),
                ('ns1', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Dengue_Antibody',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=24, max_length=3)),
                ('igm', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('igg', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Creatine',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=11, max_length=3)),
                ('creatine', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Complete_Blood_Count',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=1, max_length=3)),
                ('whitebloodcells', models.FloatField(default=0.0)),
                ('redbloodcells', models.FloatField(default=0.0)),
                ('hematocrit', models.FloatField(default=0.0)),
                ('hemaglobin', models.FloatField(default=0.0)),
                ('mcv', models.FloatField(default=0.0)),
                ('mch', models.FloatField(default=0.0)),
                ('mchc', models.FloatField(default=0.0)),
                ('plateletcount', models.FloatField(default=0.0)),
                ('rdw', models.FloatField(default=0.0)),
                ('neutrophil', models.FloatField(default=0.0)),
                ('lymphocyte', models.FloatField(default=0.0)),
                ('eosinophil', models.FloatField(default=0.0)),
                ('monocyte', models.FloatField(default=0.0)),
                ('basophil', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=5, max_length=3)),
                ('cholesterol', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Calcium',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=18, max_length=3)),
                ('calcium', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BUN',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=10, max_length=3)),
                ('bun', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BUA',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=12, max_length=3)),
                ('bua', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BloodTyping',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=2, max_length=3)),
                ('bloodgroup', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rhfactor', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Positve', max_length=8)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AST',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=13, max_length=3)),
                ('ast', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ASO',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=23, max_length=3)),
                ('aso', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ALT',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=14, max_length=3)),
                ('alt', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ALP',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=15, max_length=3)),
                ('alp', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Triglyceride',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=6, max_length=3)),
                ('triglyceride', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Urinalysis',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=19, max_length=3)),
                ('color', models.CharField(default='', max_length=20)),
                ('transparency', models.CharField(default='', max_length=20)),
                ('glucose', models.FloatField(default=0.0)),
                ('bilirubin', models.FloatField(default=0.0)),
                ('ketone', models.FloatField(default=0.0)),
                ('specific_gravity', models.FloatField(default=0.0)),
                ('blood', models.FloatField(default=0.0)),
                ('ascorbic_acid', models.FloatField(default=0.0)),
                ('creatine', models.FloatField(default=0.0)),
                ('ph_level', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('urobilinogen', models.FloatField(default=0.0)),
                ('nitrite', models.FloatField(default=0.0)),
                ('leukocytes', models.FloatField(default=0.0)),
                ('microalbumin', models.FloatField(default=0.0)),
                ('calcium', models.FloatField(default=0.0)),
                ('rbc', models.FloatField(default=0.0)),
                ('wbc', models.FloatField(default=0.0)),
                ('sec', models.FloatField(default=0.0)),
                ('amorphous_urate', models.FloatField(default=0.0)),
                ('mucus_threads', models.FloatField(default=0.0)),
                ('bacteria', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='VLDL',
            fields=[
                ('testid', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('testcode', models.CharField(default=9, max_length=3)),
                ('vldl', models.FloatField(default=0.0)),
                ('specimenid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
    ]
