# Generated by Django 4.2.6 on 2023-12-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_room_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologist_id', models.CharField(max_length=10, unique=True)),
                ('pathologist_name', models.CharField(max_length=50, unique=True)),
                ('pathologist_prc_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
