# Generated by Django 4.2.6 on 2023-12-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pathologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathologist',
            name='pathologist_id',
        ),
    ]
