# Generated by Django 5.0 on 2023-12-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medtech_name', models.CharField(max_length=50, unique=True)),
                ('medtech_prc_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
