# Generated by Django 5.0 on 2023-12-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medtech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_Blood_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_blood_cells', models.FloatField()),
                ('red_blood_cells', models.FloatField()),
                ('hematocrit', models.FloatField()),
                ('hemaglobin', models.FloatField()),
                ('mcv', models.FloatField()),
                ('mch', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_firstname', models.CharField(max_length=50, unique=True)),
                ('patient_familyname', models.CharField(max_length=50, unique=True)),
                ('patient_age', models.IntegerField()),
                ('pateint_sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('patient_birthday', models.DateField()),
                ('patient_AMD', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='pathologist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pathologist'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='test_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medtech_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medtech')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='specimen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specimen'),
        ),
    ]
