# Generated by Django 5.0 on 2023-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_complete_blood_count_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTyping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rh_factor', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='basophil',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='eosinophil',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='lymphocyte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='mchc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='monocyte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='neutrophil',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='platelet_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complete_blood_count',
            name='hemaglobin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complete_blood_count',
            name='hematocrit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complete_blood_count',
            name='mch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complete_blood_count',
            name='mcv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complete_blood_count',
            name='red_blood_cells',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='complete_blood_count',
            name='white_blood_cells',
            field=models.FloatField(default=0.0),
        ),
    ]
