# Generated by Django 5.0 on 2023-12-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bloodtyping_complete_blood_count_basophil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_blood_count',
            name='specimen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction'),
        ),
    ]
