# Generated by Django 5.0 on 2023-12-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bloodtyping_specimen_id_alp_alt_ast_bua_bun_calcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urinalysis',
            name='amorphous_urate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='ascorbic_acid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='bacteria',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='bilirubin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='blood',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='calcium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='creatine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='glucose',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='ketone',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='leukocytes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='microalbumin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='mucus_threads',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='nitrite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='ph_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='rbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='sec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='specific_gravity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='transparency',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='urobilinogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='wbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ASO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aso', models.FloatField(default=0.0)),
                ('specimen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Dengue_Antibody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igm', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('igg', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Dengue_Antigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns1', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Fecalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_appearance', models.CharField(choices=[('yellow', 'yellow'), ('brown', 'brown'), ('black', 'black')], max_length=6)),
                ('consistency', models.CharField(choices=[('formed', 'formed'), ('semi-formed', 'semi-formed'), ('watery', 'watery')], max_length=11)),
                ('mucus', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('blood', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('ova', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('cyst', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('bacteria', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=7)),
                ('other', models.CharField(max_length=50)),
                ('specimen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='FOBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fobt', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('specimen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
    ]
