# Generated by Django 5.0 on 2023-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_urinalysis_amorphous_urate_urinalysis_ascorbic_acid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_birthday',
            new_name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pateint_sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_AMD',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_familyname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_firstname',
        ),
        migrations.AddField(
            model_name='patient',
            name='patientfirstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientlastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientmiddlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='requesting_physician',
            field=models.CharField(default='DefaultPhysicianName', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8),
        ),
    ]
