# Generated by Django 5.0 on 2023-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_patient_age_patient_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alp',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='alt',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='aso',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='ast',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='bloodtyping',
            old_name='blood_type',
            new_name='bloodgroup',
        ),
        migrations.RenameField(
            model_name='bloodtyping',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='bua',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='bun',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='calcium',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='cholesterol',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='complete_blood_count',
            old_name='platelet_count',
            new_name='plateletcount',
        ),
        migrations.RenameField(
            model_name='complete_blood_count',
            old_name='red_blood_cells',
            new_name='rdw',
        ),
        migrations.RenameField(
            model_name='complete_blood_count',
            old_name='white_blood_cells',
            new_name='redbloodcells',
        ),
        migrations.RenameField(
            model_name='complete_blood_count',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='creatine',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='dengue_antibody',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='dengue_antigen',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='esr',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='fbs',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='fecalysis',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='fobt',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='hdl',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='ldl',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='potassium',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='pregnancy_test',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='sodium',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='specimen',
            old_name='medtech_id',
            new_name='medtechid',
        ),
        migrations.RenameField(
            model_name='specimen',
            old_name='patient_id',
            new_name='patientid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='pathologist_id',
            new_name='pathoid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='patient_id',
            new_name='patientid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='triglyceride',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='urinalysis',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RenameField(
            model_name='vldl',
            old_name='specimen_id',
            new_name='specimenid',
        ),
        migrations.RemoveField(
            model_name='alp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bloodtyping',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bloodtyping',
            name='rh_factor',
        ),
        migrations.RemoveField(
            model_name='bua',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bun',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calcium',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cholesterol',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complete_blood_count',
            name='id',
        ),
        migrations.RemoveField(
            model_name='creatine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dengue_antibody',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dengue_antigen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='esr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fbs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fecalysis',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fobt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hdl',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ldl',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medtech',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medtech',
            name='medtech_name',
        ),
        migrations.RemoveField(
            model_name='medtech',
            name='medtech_prc_id',
        ),
        migrations.RemoveField(
            model_name='pathologist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pathologist',
            name='pathologist_name',
        ),
        migrations.RemoveField(
            model_name='pathologist',
            name='pathologist_prc_id',
        ),
        migrations.RemoveField(
            model_name='potassium',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pregnancy_test',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sodium',
            name='id',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='test_code',
        ),
        migrations.RemoveField(
            model_name='triglyceride',
            name='id',
        ),
        migrations.RemoveField(
            model_name='urinalysis',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vldl',
            name='id',
        ),
        migrations.AddField(
            model_name='alp',
            name='testcode',
            field=models.CharField(default=15, max_length=3),
        ),
        migrations.AddField(
            model_name='alp',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='alt',
            name='testcode',
            field=models.CharField(default=14, max_length=3),
        ),
        migrations.AddField(
            model_name='alt',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='aso',
            name='testcode',
            field=models.CharField(default=23, max_length=3),
        ),
        migrations.AddField(
            model_name='aso',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ast',
            name='testcode',
            field=models.CharField(default=13, max_length=3),
        ),
        migrations.AddField(
            model_name='ast',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bloodtyping',
            name='rhfactor',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Positve', max_length=8),
        ),
        migrations.AddField(
            model_name='bloodtyping',
            name='testcode',
            field=models.CharField(default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='bloodtyping',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bua',
            name='testcode',
            field=models.CharField(default=12, max_length=3),
        ),
        migrations.AddField(
            model_name='bua',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bun',
            name='testcode',
            field=models.CharField(default=10, max_length=3),
        ),
        migrations.AddField(
            model_name='bun',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='calcium',
            name='testcode',
            field=models.CharField(default=18, max_length=3),
        ),
        migrations.AddField(
            model_name='calcium',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cholesterol',
            name='testcode',
            field=models.CharField(default=5, max_length=3),
        ),
        migrations.AddField(
            model_name='cholesterol',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='testcode',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='complete_blood_count',
            name='whitebloodcells',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='creatine',
            name='testcode',
            field=models.CharField(default=11, max_length=3),
        ),
        migrations.AddField(
            model_name='creatine',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dengue_antibody',
            name='testcode',
            field=models.CharField(default=24, max_length=3),
        ),
        migrations.AddField(
            model_name='dengue_antibody',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dengue_antigen',
            name='testcode',
            field=models.CharField(default=25, max_length=3),
        ),
        migrations.AddField(
            model_name='dengue_antigen',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='esr',
            name='testcode',
            field=models.CharField(default=3, max_length=3),
        ),
        migrations.AddField(
            model_name='esr',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fbs',
            name='testcode',
            field=models.CharField(default=4, max_length=3),
        ),
        migrations.AddField(
            model_name='fbs',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fecalysis',
            name='pus_cells',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fecalysis',
            name='rbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fecalysis',
            name='testcode',
            field=models.CharField(default=21, max_length=3),
        ),
        migrations.AddField(
            model_name='fecalysis',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fobt',
            name='testcode',
            field=models.CharField(default=22, max_length=3),
        ),
        migrations.AddField(
            model_name='fobt',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hdl',
            name='testcode',
            field=models.CharField(default=7, max_length=3),
        ),
        migrations.AddField(
            model_name='hdl',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ldl',
            name='testcode',
            field=models.CharField(default=8, max_length=3),
        ),
        migrations.AddField(
            model_name='ldl',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medtech',
            name='medtechid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medtech',
            name='medtechname',
            field=models.CharField(default='Medtech Name', max_length=100),
        ),
        migrations.AddField(
            model_name='medtech',
            name='prcid',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='pathologist',
            name='pathoid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pathologist',
            name='pathoname',
            field=models.CharField(default='Patho Name', max_length=100),
        ),
        migrations.AddField(
            model_name='pathologist',
            name='prcid',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='potassium',
            name='testcode',
            field=models.CharField(default=17, max_length=3),
        ),
        migrations.AddField(
            model_name='potassium',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pregnancy_test',
            name='testcode',
            field=models.CharField(default=20, max_length=3),
        ),
        migrations.AddField(
            model_name='pregnancy_test',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sodium',
            name='testcode',
            field=models.CharField(default=16, max_length=3),
        ),
        migrations.AddField(
            model_name='sodium',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='specimen',
            name='specimenid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='testcode',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='testid',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='triglyceride',
            name='testcode',
            field=models.CharField(default=6, max_length=3),
        ),
        migrations.AddField(
            model_name='triglyceride',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='testcode',
            field=models.CharField(default=19, max_length=3),
        ),
        migrations.AddField(
            model_name='urinalysis',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vldl',
            name='testcode',
            field=models.CharField(default=9, max_length=3),
        ),
        migrations.AddField(
            model_name='vldl',
            name='testid',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fecalysis',
            name='other',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
